- name: Ansible task
  hosts: ubuntu
  user: root
  become: yes
  tasks:
    - name: Update Package Lists (apt-get update)
      become: yes  # To run the command with sudo
      apt:
        update_cache: yes

    - name: Install Apache 
      apt:
        name: apache2
        state: present

    - name: Start Apache 
      service:
        name: apache2
        state: started

    - name: Download Template
      get_url:
        url:  https://www.free-css.com/assets/files/free-css-templates/download/page294/primecare.zip
        dest: /tmp/

    - name: Install unzip 
      apt:
        name: unzip
        state: present

    - name: Extract Zip Template
      unarchive:
        src: /tmp/primecare.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Fix file permissions
      file:
        path: /var/www/html/
        owner: root
        group: root
        mode: '1777'

